name: Linux Build

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    name: Compile and test on Linux
    runs-on: ubuntu-latest
    container:
      image: wichtounet/cpp:latest
    strategy:
        matrix:
            compiler: [gcc, clang]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Build binaries
      run: make -j5 ./release_debug/bin/eddic compiler=${{ matrix.compiler }}

    - name: Build tests
      run: make -j5 ./release_debug/bin/test compiler=${{ matrix.compiler }}

    - name: Run tests
      run: ./release_debug/bin/test compiler=${{ matrix.compiler }}
