name: Linux Build

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    name: Compile and test on Linux
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [ubuntu-24.04]
            compiler: [g++-14,clang++-18]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install dependencies
      run: sudo apt install libboost-all-dev

    - name: Install GCC compiler
      run: sudo apt install g++-14

    - name: install LLVM compiler
      run: |
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo apt-add-repository "deb http://apt.llvm.org/noble/ llvm-toolchain-noble-18 main"
          sudo apt update
          sudo apt install clang-18

    - name: Build binaries
      env:
          CXX: ${{ matrix.compiler }}
      run: make -j5 ./release_debug/bin/eddic

    - name: Build tests
      env:
          CXX: ${{ matrix.compiler }}
      run: make -j5 ./release_debug/bin/test

    - name: Run tests
      run: ./release_debug/bin/test
